apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealm
metadata:
  name: {{ .Values.keycloak.name }}-realm
  namespace: {{ .Values.keycloak.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  realm:
    realm: sample-realm
    enabled: true
    displayName: Sample Realm
  instanceSelector:
    matchLabels:
      app: {{ .Values.keycloak.name }}
